# Generated by Django 5.0.4 on 2024-04-15 16:06

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=event.models.avatarupload
            ),
        ),
    ]
