# Generated by Django 5.0.4 on 2024-09-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
