# Generated by Django 5.0.4 on 2024-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_vote_is_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='amount_rewarded',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
