# Generated by Django 5.0.4 on 2024-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="market",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming Market"),
                    ("active", "Active Market"),
                    ("recent", "Recent Market"),
                ],
                default="upcoming",
                max_length=50,
            ),
        ),
    ]
