# Generated by Django 5.0.4 on 2024-04-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_event_market"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="market",
        ),
    ]
