# Generated by Django 5.0.4 on 2024-09-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_vote_amount_rewarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='amount_rewarded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
