# Generated by Django 4.2.3 on 2024-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
