# Generated by Django 5.0.4 on 2024-09-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_vote_amount_rewarded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="update_event_tx_receipt",
        ),
    ]
