# Generated by Django 4.2.3 on 2024-07-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_event_end_date_alter_event_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="resolution_date",
            field=models.DateTimeField(),
        ),
    ]
