# Generated by Django 4.2.3 on 2024-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_alter_event_resolution_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="token_volume",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
