# Generated by Django 5.0.4 on 2024-08-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_event_token_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="min_token_stake",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="token_staked",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
