# Generated by Django 5.0.4 on 2024-08-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_event_min_token_stake_vote_token_staked_vote_tx_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="min_token_stake",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="token_volume",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
