# Generated by Django 5.0.4 on 2024-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_alter_event_min_token_stake_alter_event_token_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="min_token_stake",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="token_volume",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
