# Generated by Django 5.0.4 on 2024-08-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_alter_event_min_token_stake_alter_event_token_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="amount_rewarded",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
