# Generated by Django 5.0.4 on 2024-08-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0012_vote_amount_rewarded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="user",
            new_name="account",
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
    ]
