# Generated by Django 5.0.4 on 2024-08-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_rename_real_result_event_final_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="close_event_tx_receipt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="create_event_tx_receipt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
