# Generated by Django 5.0.4 on 2024-08-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0016_event_close_event_tx_receipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
