# Generated by Django 5.0.4 on 2024-08-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0017_event_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="update_event_tx_receipt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
