# Generated by Django 5.0.4 on 2024-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0018_event_update_event_tx_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_id",
        ),
        migrations.AddField(
            model_name="event",
            name="burn_share",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
