# Generated by Django 5.0.4 on 2024-08-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0012_vote_amount_rewarded"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Account",
        ),
    ]
