# Generated by Django 5.0.4 on 2024-08-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_user_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
